### ISSUE TITLE
IKAP Error: could not find function "FindVariableGenes"

### ISSUE THREAD

**Issue by biobug16** [NHLBI-BCB/IKAP#2]
Hi @NHLBI-BCB 
I am trying to use IKAP for a merged Seurat's object but getting a weired error about unable to find the function "FindVariableGenes". I also checked for ?FindVariableGenes() which is working perfectly fine.

```
Error in FindVariableGenes(sobj, mean.function = ExpMean, dispersion.function = LogVMR,  : 
  could not find function "FindVariableGenes"
In addition: Warning message:
In IKAP(inhouse_wt_norm_log_var_feat.integrated, out.dir = "./IKAP") :
  nUMIpercent.mitonot in Seurat metadata: skipped for regression.
```
Is there anyone who has encountered this issue before and can guide how to resolve this issue?

Thanks

**Comment by vincr04** [comment]
I haven't seen this issue but maybe the reason is that you are using the code that is made for Seurat version <3? If your object is in Seurat v3 you will need to use the IKAP_Seurat3.R code (just download the file and use the 'source' command to load the functions into your environment). 
Hope this helps!

**Comment by Drosophilist** [comment]
Hello,
I have encountered the same issue. Followed README.md to install.
Cheers

**Comment by tiagobrc** [comment]
IKAP_Seurat3.R works! WOuld be nice to see this script integrated into the main package! Thanks
